# Generated by Django 3.2.9 on 2021-11-11 12:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_name', models.CharField(max_length=255, unique=True)),
                ('choice1', models.CharField(choices=[('1', 'Choose'), ('2', 'Name'), ('3', 'Job'), ('4', 'Email'), ('5', 'Domain'), ('6', 'Phone number'), ('7', 'Company'), ('8', 'Text'), ('9', 'Age'), ('10', 'Address'), ('11', 'Date')], default='1', max_length=9)),
                ('choice2', models.CharField(choices=[('1', 'Choose'), ('2', 'Name'), ('3', 'Job'), ('4', 'Email'), ('5', 'Domain'), ('6', 'Phone number'), ('7', 'Company'), ('8', 'Text'), ('9', 'Age'), ('10', 'Address'), ('11', 'Date')], default='1', max_length=9)),
                ('choice3', models.CharField(choices=[('1', 'Choose'), ('2', 'Name'), ('3', 'Job'), ('4', 'Email'), ('5', 'Domain'), ('6', 'Phone number'), ('7', 'Company'), ('8', 'Text'), ('9', 'Age'), ('10', 'Address'), ('11', 'Date')], default='1', max_length=9)),
                ('choice4', models.CharField(choices=[('1', 'Choose'), ('2', 'Name'), ('3', 'Job'), ('4', 'Email'), ('5', 'Domain'), ('6', 'Phone number'), ('7', 'Company'), ('8', 'Text'), ('9', 'Age'), ('10', 'Address'), ('11', 'Date')], default='1', max_length=9)),
                ('choice5', models.CharField(choices=[('1', 'Choose'), ('2', 'Name'), ('3', 'Job'), ('4', 'Email'), ('5', 'Domain'), ('6', 'Phone number'), ('7', 'Company'), ('8', 'Text'), ('9', 'Age'), ('10', 'Address'), ('11', 'Date')], default='1', max_length=9)),
                ('choice6', models.CharField(choices=[('1', 'Choose'), ('2', 'Name'), ('3', 'Job'), ('4', 'Email'), ('5', 'Domain'), ('6', 'Phone number'), ('7', 'Company'), ('8', 'Text'), ('9', 'Age'), ('10', 'Address'), ('11', 'Date')], default='1', max_length=9)),
                ('choice7', models.CharField(choices=[('1', 'Choose'), ('2', 'Name'), ('3', 'Job'), ('4', 'Email'), ('5', 'Domain'), ('6', 'Phone number'), ('7', 'Company'), ('8', 'Text'), ('9', 'Age'), ('10', 'Address'), ('11', 'Date')], default='1', max_length=9)),
                ('choice8', models.CharField(choices=[('1', 'Choose'), ('2', 'Name'), ('3', 'Job'), ('4', 'Email'), ('5', 'Domain'), ('6', 'Phone number'), ('7', 'Company'), ('8', 'Text'), ('9', 'Age'), ('10', 'Address'), ('11', 'Date')], default='1', max_length=9)),
                ('choice9', models.CharField(choices=[('1', 'Choose'), ('2', 'Name'), ('3', 'Job'), ('4', 'Email'), ('5', 'Domain'), ('6', 'Phone number'), ('7', 'Company'), ('8', 'Text'), ('9', 'Age'), ('10', 'Address'), ('11', 'Date')], default='1', max_length=9)),
                ('choice10', models.CharField(choices=[('1', 'Choose'), ('2', 'Name'), ('3', 'Job'), ('4', 'Email'), ('5', 'Domain'), ('6', 'Phone number'), ('7', 'Company'), ('8', 'Text'), ('9', 'Age'), ('10', 'Address'), ('11', 'Date')], default='1', max_length=9)),
                ('name1', models.CharField(default='None', max_length=255)),
                ('name2', models.CharField(default='None', max_length=255)),
                ('name3', models.CharField(default='None', max_length=255)),
                ('name4', models.CharField(default='None', max_length=255)),
                ('name5', models.CharField(default='None', max_length=255)),
                ('name6', models.CharField(default='None', max_length=255)),
                ('name7', models.CharField(default='None', max_length=255)),
                ('name8', models.CharField(default='None', max_length=255)),
                ('name9', models.CharField(default='None', max_length=255)),
                ('name10', models.CharField(default='None', max_length=255)),
                ('order1', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('order2', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('order3', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('order4', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('order5', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('order6', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('order7', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('order8', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('order9', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('order10', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('min_age', models.IntegerField(default=0)),
                ('max_age', models.IntegerField(default=100)),
                ('quantity_of_sentences', models.IntegerField(default=1)),
                ('rows', models.IntegerField(default=1)),
                ('task_progress', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('upload', models.FileField(blank=True, upload_to='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
