# Generated by Django 3.2.9 on 2022-02-12 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_auto_20220211_1423'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schemecolumn',
            unique_together={('scheme', 'order')},
        ),
    ]
